In [1]:
import numpy as np
import capsol

In [27]:
r = np.array([ 0. ,  0.5,  1.1 ,  1.8,  2.5 ,  3.3 , 4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])
z = np.linspace(-5, 10, 31) # Example z grid

In [28]:
r

array([ 0. ,  0.5,  1.1,  1.8,  2.5,  3.3,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [29]:
dr = np.diff(r)
dz = np.diff(z)

dR, dZ = np.meshgrid(dr, dz)

In [30]:
R, Z = np.meshgrid(r, z)

In [31]:
params = dict(hcone=5, dcant=1.0, rcant=5.0)
spm_tip = capsol.body(R, Z, hcone=5, dcant=1.0, rcant=5.0)

In [32]:
R[spm_tip]

array([0. , 0.5, 1.1, 1.8, 2.5, 3.3, 4. , 4.5, 5. , 0. , 0.5, 1.1, 1.8,
       2.5, 3.3, 4. , 4.5, 5. ])

In [33]:
Z[spm_tip]

array([5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5.5, 5.5, 5.5, 5.5,
       5.5, 5.5, 5.5, 5.5, 5.5])

In [34]:
b = np.ones_like(R) # set the boundaries

# Specify boundaries
b[0, :] = 0.0 # Potential fixed to zero at the boundaries...
b[-1, :] = 0.0
b[:, -1] = 0.0 

u = np.zeros_like(R)
u[spm_tip] = 1.0 # Potential is 1 V on the cantilever...

n_sample = 2

In [35]:
# samp = capsol.sample(Z, n_sample)

In [36]:
Vn = np.pi * (R[:-1, 1:] + R[:-1, :-1]) * dR * dZ

In [47]:
# Determine the phi that minimizes the functional, given the constraints...


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [57]:
du_dz = np.diff(u[:, :-1], axis=0) / dZ
du_dr = np.diff(u[:-1, :], axis=1) / dR

In [65]:
np.sum((du_dz**2 + du_dr**2) * 0.5 * 1 * Vn)

223.0530784048753

In [68]:
du_dz.ravel().shape # Ravel the arrays to get a constant pt...

(540,)

In [45]:
Vn.ravel().size

540

In [38]:
R[0, 1], R[0, 2]

(0.5, 1.1)

In [40]:
(1.1**2 - 0.5**2) * np.pi * 0.5

1.507964473723101

In [69]:
# Quadradic functional...


In [70]:
# gradient_phi_n is linear...

In [74]:
n, m = u.shape

In [97]:
n, m = 5, 5

In [98]:
# 8 rows
# 7 columns

u = np.zeros(shape=(n, m))

u[2,2] = 1.0

In [163]:
u_node = np.zeros(shape=((n-1)*(m-1), n*m))

drows = np.zeros(shape=(n*m, n*m))
tot = n*m
for i in range(n): # Iterate over rows
    for j in range(m): # Iterate over columns...
        ij = i*m+j # current row...
        if i < (n-1):
        # My neighbors are one row above and below...
        # Eest = u_row_minus_1 - u_row_plus_1 (those are the only non-zero elements)
            above = (i+1)*m+j
            drows[ij, above] = -1.0
            u_node[ij, above] = 1.0
        if i > 0:
            below = (i-1)*m + j
            drows[ij, below] = 1.0
            u_node[ij, below] = 1.0

dcols = np.zeros(shape=(n*m, n*m))
for i in range(n): # Iterate over rows
    for j in range(m): # Iterate over columns...
        ij = i*m+j # current row...
        # My neighbors are one row above and below...
        # Eest = u_row_minus_1 - u_row_plus_1 (those are the only non-zero elements)
        if j < (m-1):
            right = (i)*m+j+1
            dcols[ij, right] = -1.0
            u_node[ij, right] = 1.0
        if j > 0:
            left = (i)*m + j-1
            dcols[ij, left] = 1.0
            u_node[ij, left] = 1.0


IndexError: index 16 is out of bounds for axis 0 with size 16

In [162]:
u_node = u_node / u_node.sum(axis=1)

In [ ]:
u_node

$$(D_c \, u)^T (D_c \, u) \\
\frac{1}{2}  u^T (D_c^T D_c + D_z^T D_z) (v \epsilon u) - (\rho (v_ u)
$$

$ (D_c \, u) ^2$

In [153]:
(dcols @ ur)**2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [124]:
u.ravel().T @ dcols.T @ dcols @ u.ravel()

2.0

In [127]:
def check_symmetric(a, tol=1e-8):
    return np.all(np.abs(a-a.T) < tol)

In [128]:
H = (dcols.T @ dcols + drows.T @ drows) / 4.0

In [132]:
from scipy import linalg

In [133]:
linalg.norm(H)

19.8997487421324

In [119]:
(dcols @ u.ravel()).T @ (dcols @ u.ravel())

2.0

In [100]:
drows @ u.ravel() @ drows.T

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.])

In [112]:
np.dot(drows @ u.ravel(), drows @ u.ravel())

2.0

In [104]:
b = np.ones_like(u)
b[0, :] = 0
b[-1, :] = 0
b[:, 0] = 0
b[:, -1] = 0

In [134]:
ur = u.ravel()

In [140]:
ur.T @ H @ ur


4.0

In [146]:
b

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [142]:
linalg.solve(H, b.ravel())

array([1.57880435, 0.47368421, 1.625     , 0.57894737, 1.4673913 ,
       0.42105263, 1.24456522, 0.63157895, 1.25543478, 0.47368421,
       1.5326087 , 0.84210526, 1.82880435, 0.84210526, 1.5326087 ,
       0.47368421, 1.25543478, 0.63157895, 1.24456522, 0.42105263,
       1.4673913 , 0.57894737, 1.625     , 0.47368421, 1.57880435])

In [147]:
H @ ur

array([ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  4.,
        0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.])

In [189]:
uu = np.array([
    [0, 0.2, 0.5],
    [0, 1.0, 0.5],
    [-0.1, 0.2, 0.3],
    [-0.1, 0.0, 0.1]
])

In [209]:
uu.ravel()

array([ 0. ,  0.2,  0.5,  0. ,  1. ,  0.5, -0.1,  0.2,  0.3, -0.1,  0. ,
        0.1])

In [194]:
n, m = uu.shape
N_out = (n-1)*(m-1)
N_in = n*m

In [205]:
uu1 = np.zeros(shape=(N_out, N_in))

In [253]:
def Au_func(A_u, i_out, n, m):
    # i_out is what mesh we are in output space.
    # i_col is what node we are in input space.
    out_row = int(i_out / (m-1)) # Rows change slowly
    out_col = i_out - out_row * (m-1)
    inds = [out_row*m+out_col, out_row*m+out_col+1, (out_row+1)*m+out_col, (out_row+1)*m+out_col+1] 
    for ind in inds:
        A_u[i_out, ind] = 0.25

In [349]:
def E_row_func(A_u, i_out, n, m):
    # i_out is what mesh we are in output space.
    # i_col is what node we are in input space.
    out_row = int(i_out / (m-1)) # Rows change slowly
    out_col = i_out - out_row * (m-1)
    A_u[i_out, out_row*m+out_col] = 1/2
    A_u[i_out, out_row*m+out_col+1] = 1/2
    A_u[i_out, (out_row+1)*m+out_col] = -1/2
    A_u[i_out, (out_row+1)*m+out_col+1] = -1/2
    
def E_col_func(A_u, i_out, n, m):
    # i_out is what mesh we are in output space.
    # i_col is what node we are in input space.
    out_row = int(i_out / (m-1)) # Rows change slowly
    out_col = i_out - out_row * (m-1)
    A_u[i_out, out_row*m+out_col+1] = -1/2
    A_u[i_out, (out_row+1)*m+out_col+1] = -1/2
    A_u[i_out, (out_row+1)*m+out_col] = 1/2
    A_u[i_out, out_row*m+out_col] = 1/2

    

def make_A(func, n, m):
    N_out = (n-1)*(m-1)
    N_in = n*m
    A_u = np.zeros(shape=(N_out, N_in))
    for i_out in range(N_out):
        func(A_u, i_out, n, m)
    return A_u

In [350]:
A_u = make_A(Au_func, n, m)
E_ru = make_A(E_row_func, n, m)
E_cu = make_A(E_col_func, n, m)


In [351]:
u_node = (A_u @ uu.ravel()).reshape((n-1, -1))
u_node

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 12 is different from 20)

In [352]:
E_r_node = (E_ru @ uu.ravel()).reshape((n-1, -1))
E_c_node = (E_cu @ uu.ravel()).reshape((n-1, -1))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 12 is different from 20)

$$  
I[u] = \frac{1}{2} u^T E_c^T \, D_{\varepsilon} D_{v}  \, E_c u +
\frac{1}{2}  u^T E_r^T \,D_{\varepsilon} D_{v}   \, E_r u -  u^T D_{v}\rho \\
\frac{d I}{d u} = E_c^T \, D_{\varepsilon} D_{v} E_c u +
 E_r^T \,D_{\varepsilon} D_{v} E_r u -  D_{v}\rho = 0 \\
 D_{v} \rho = (E_c^T \, D_{\varepsilon} D_{v} E_c +
 E_r^T \,D_{\varepsilon} D_{v} E_r) u
$$
so that we have the vector
$$ b =  D_{v} \rho \\
   A = E_c^T \, D_{\varepsilon} D_{v} E_c +
 E_r^T \,D_{\varepsilon} D_{v} E_r
$$

In [353]:
A_tot = E_ru.T @ E_ru + E_cu.T @ E_cu

In [354]:
E_ru.T @ E_ru @ uu.ravel()

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 12 is different from 20)

In [519]:
symmetric

NameError: name 'symmetric' is not defined

In [500]:
uu2 = np.array([
    [3.0, 3.0, 3.0, 3.0, 3.0],
    [2.5, 0.0, 0, 0, 2.5],
    [2, 0.0, 0, 0, 2],
    [1.5, 0.0, 0, 0, 1.5],
    [1, 1, 1, 1, 1],
])

nz = np.nonzero(uu2.ravel())[0]


print(nz)

N_in = len(uu2.ravel())

zeros = np.array([x for x in np.arange(N_in) if x not in nz])

perm_mat = np.zeros((N_in, N_in))

for i in range(N_in):
    if i < len(nz):
        perm_mat[i, nz[i]] = 1
    else:
        perm_mat[i, zeros[i-len(nz)]] = 1


n, m = uu2.shape
A_u = make_A(Au_func, n, m)
E_ru = make_A(E_row_func, n, m)
E_cu = make_A(E_col_func, n, m)
A_tot = E_ru.T @ E_ru + E_cu.T @ E_cu
b1 = -A_tot @ uu2.ravel()
A_free = np.copy(A_tot)

[ 0  1  2  3  4  5  9 10 14 15 19 20 21 22 23 24]


In [501]:
A_varying = (A_tot @ perm_mat)[len(nz):, len(nz):]

In [502]:
b_varying = (perm_mat @ b1)[len(nz):]

In [503]:
U, s, vh = linalg.svd(A_varying)
mask = s < 1e-15
si = 1/s
si[mask] = 0

In [512]:
A_varying

array([[-0.5,  0. ,  0. , -0.5,  0. , -0.5,  0. ,  0. ,  0. ],
       [ 0. , -0.5,  0. ,  0. , -0.5,  0. , -0.5,  0. ,  0. ],
       [-0.5,  0. , -0.5,  0. ,  0. , -0.5,  0. , -0.5,  0. ],
       [ 0. , -0.5,  0. ,  0. ,  0. ,  0. , -0.5,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [518]:
symm A_tot

array([[ 0.5,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. , -0.5,  0. , -0.5,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ,  0. ,  0. , -0.5,  0. , -0.5,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. , -0.5,  0. , -0.5,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0. ,  0. , -0.5,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ],
       [ 0. , -0.5,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  

In [517]:
np.linalg.matrix_rank(A_tot)

23

In [505]:
x_solve = vh @ np.diag(si) @ U.T @ b_varying

In [506]:
x_solve

array([-7.56129295e-01,  6.86327763e-02, -4.26986719e+00, -2.12312075e+00,
        1.13750413e+00, -6.03147963e-15,  7.12307009e-01, -1.04315172e+01,
       -6.00552267e+00])

In [507]:
uu_solved = perm_mat.T @ np.r_[(perm_mat @ uu2.ravel() )[:len(nz)], x_solve]

In [508]:
(A_u @ uu_solved).reshape((4, -1))

array([[ 1.93596768,  1.32812587,  0.4496914 ,  1.0575332 ],
       [ 0.40518749, -0.41827829, -0.76593257,  0.0575332 ],
       [ 0.52229656, -2.6762067 , -3.82488393, -0.62638067],
       [ 1.05307675, -1.92980255, -3.60925997, -0.62638067]])

In [509]:
A_u.shape

(16, 25)

In [510]:
from scipy import linalg

In [511]:
out = linalg.solve(A_free[4:, 4:], b1[4:])

In [385]:
linalg.perm

AttributeError: module 'scipy.linalg' has no attribute 'perm'

In [386]:
out = np.zeros(n*m)
out[0:4] = 1.0

In [440]:
b_varying

array([-0.5, -1. , -1. , -1. , -0.5,  0.5,  1. ,  1. ,  1. ,  0.5,  0. ,
        0. ,  0. ,  0. ,  0. ])

In [388]:
 linalg.solve(A_tot,out).reshape()

/var/folders/zn/x8ct2v5d1z714b45ycxv1hhc0000gn/T/ipykernel_33482/4231187275.py:1: LinAlgWarning: Ill-conditioned matrix (rcond=5.55112e-18): result may not be accurate.
  linalg.solve(A_tot,out).reshape()


TypeError: reshape() takes exactly 1 argument (0 given)

In [390]:
b0 = A_tot @ uu2.ravel()

In [391]:
A_tot[:5, :5]

array([[ 0.5,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. , -0.5],
       [ 0. ,  0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0.5,  0. ],
       [ 0. , -0.5,  0. ,  0. ,  1. ]])

In [392]:
b0

array([ 0.5,  0. ,  1. ,  0.5,  0. , -1. , -0.5, -0.5,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ])

In [393]:
linalg.solve(A_tot, b0)

/var/folders/zn/x8ct2v5d1z714b45ycxv1hhc0000gn/T/ipykernel_33482/4129082772.py:1: LinAlgWarning: Ill-conditioned matrix (rcond=5.55112e-18): result may not be accurate.
  linalg.solve(A_tot, b0)


array([ 1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., -0.,  0., -0.,  0.])

In [366]:
A_tot[:10, :10]*2

array([[ 1.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0., -1.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  2.,  0.,  0., -1.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  2.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0., -1.,  0.,  0.,  4.,  0.,  0., -1.,  0.],
       [ 0., -1.,  0., -1.,  0.,  0.,  4.,  0.,  0., -1.],
       [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0., -1.,  0.,  0.,  4.]])

In [332]:
np.r_[uu2.ravel()[:3], out].reshape((n, m))

array([[0.5, 1. , 0.5],
       [1. , 0.5, 1. ],
       [0.5, 1. , 0.5],
       [1. , 0.5, 1. ]])

In [188]:
inds_grid = np.array([[i*10 + j for j in range(4)] for i in range(4)])
inds_grid

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [181]:
inds.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33])

In [176]:
u.shape

(5, 5)

In [175]:
Vn.shape

(30, 18)

In [ ]:
np.diag()

In [171]:
n1 = n-1
m1 = m -1
u_node = np.zeros(shape=((n-1)*(m-1), n*m))

drows = np.zeros(shape=((n-1)*(m-1), n*m))
for i in range(n-1): # Iterate over rows
    for j in range(m-1): # Iterate over columns...
        ij = i*m+j # current row...
        # My neighbors are one row above and below...
        # Eest = u_row_minus_1 - u_row_plus_1 (those are the only non-zero elements)
        above = (i+1)*m+j
        drows[ij, above] = -1.0
        u_node[ij, above] = 1.0
        below = (i-1)*m + j
        drows[ij, below] = 1.0
        u_node[ij, below] = 1.0

dcols = np.zeros(shape=(n*m, n*m))
for i in range(n): # Iterate over rows
    for j in range(m): # Iterate over columns...
        ij = i*m+j # current row...
        # My neighbors are one row above and below...
        # Eest = u_row_minus_1 - u_row_plus_1 (those are the only non-zero elements)
        if j < (m-1):
            right = (i)*m+j+1
            dcols[ij, right] = -1.0
            u_node[ij, right] = 1.0
        if j > 0:
            left = (i)*m + j-1
            dcols[ij, left] = 1.0
            u_node[ij, left] = 1.0



3

$ A x = b_0$ (for now, this is 0)... 
Then take $x = x_1 + y$. Then we have
$$A y = b_0 - A x_1$$
But $y$ cannot 